### ISSUE TITLE
SSL/TLS

### ISSUE THREAD

**Issue by MaximeDereymez** [ECOM2017-MesLocationsVacances/MesLocationsVacances#21]
Prise en charge de connexion par https
https://certbot.eff.org/
https://hub.docker.com/r/certbot/certbot/

**Comment by Antoine38660** [comment]
J'ai intégré le SSL sur le front : https://d14yfjruasuu7z.cloudfront.net

**Comment by Antoine38660** [comment]
Finalement géré sur le back grace a HAproxy
