### ISSUE TITLE
Mise en place AWS + CI

### ISSUE THREAD

**Issue by TimotheeLemaire** [ECOM2017-MesLocationsVacances/MesLocationsVacances#3]

**Comment by TimotheeLemaire** [comment]
Application déployée. pb mise à jour ?

**Comment by Antoine38660** [comment]
J'ai "pris en main" la partie ECR d'AWS pour le déploiement de conteneur docker. Effectivement la mise à jour ne se fait pas (lors d'un redéploiement), WIP :smile:

**Comment by Antoine38660** [comment]
Update: je commence à bien comprendre _ECR_ d'AWS ! J'en profite pour intégrer directement CircleCI qui nous servira à l'integration continue. Je touche au but :smiley:
